version: '3.9'

services:
  discordtts:
    image: ghcr.io/r2iz/discord-tts:latest
    hostname: discordtts
    container_name: discordtts__discordtts

    restart: unless-stopped

    depends_on:
      - voicevox
      - emoji-setup

    environment:
      VOICEVOX_HOST: http://voicevox:50021
      PERSISTENT_PATH: /var/discordtts/db/db.json
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      SOZAI_INDEX_URL: https://synchthia-sounds.storage.googleapis.com/index.json

    volumes:
      - type: volume
        source: data
        target: /var/discordtts/

    networks:
      - discordtts_default

    deploy:
      resources:
        limits:
          memory: 512m

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    platform: linux/arm64

    hostname: voicevox
    container_name: discordtts__voicevox

    restart: unless-stopped

    expose:
      - 50021

    networks:
      - discordtts_default

    deploy:
      resources:
        limits:
          memory: 512m

  emoji-setup:
    image: alpine:latest
    container_name: discordtts__emoji-setup

    restart: "no"

    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /var/discordtts/emoji-ja &&
        git clone https://github.com/yagays/emoji-ja /var/discordtts/emoji-ja &&
        mkdir -p /var/discordtts/db
      "

    volumes:
      - type: volume
        source: data
        target: /var/discordtts/

    networks:
      - discordtts_default

    deploy:
      resources:
        limits:
          memory: 64m

volumes:
  data:
    name: discordtts__data

networks:
  discordtts_default:
    name: discordtts__default